name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERUSERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERPASSWORD }}
    - name: Build and push the API image
      run: docker build -f "src/Hosts/CiCdApp.Hosts.Api/Dockerfile" . --push -t prostoaleks/cicd-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy through ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSHHOST }}
          password: ${{ secrets.SSHKEY }}
          username: ${{ secrets.SSHUSER }}
          script: |
            docker pull prostoaleks/cicd-api:latest && \
            docker stop cicd && \
            docker rm cicd && \
            docker run --name cicd -p 5000:80 -e ASPNETCORE_ENVIRONMENT=Development -d prostoaleks/cicd-api:latest
